-- Generated by scripts/gen-hsluv-palette.lua. Do not edit by hand.
--
-- Dawn: pale and cool, every colour kept off the gamut wall.
--
-- Built from HSLuv specs so every ramp steps evenly in perceived
-- lightness. Edit the spec in the generator and run it again.

return {
  bg_stark = '#0B0B0A',
  bg_dim = '#141312',
  bg0 = '#1C1B1A',
  bg1 = '#21201F',
  bg2 = '#262524',
  bg3 = '#2B2A29',
  bg4 = '#302F2E',
  bg5 = '#353533',
  bg_select = '#3E3E37',
  bg_bright = '#4F4E44',
  fg_bright = '#F1DDBC',
  fg0 = '#E9D1A8',
  fg1 = '#DFC69A',
  fg2 = '#D5BB8B',
  fg3 = '#CBB07D',
  fg4 = '#C1A56E',
  fg5 = '#B79A5F',
  fg_dim = '#C3B193',
  grey0 = '#43433A',
  grey1 = '#58584D',
  grey2 = '#6E6E60',
  blue = '#849070',
  cyan = '#809A7D',
  green = '#959D6E',
  green_dim = '#787C5B',
  orange = '#D5895C',
  orange_dim = '#936243',
  red = '#CA9177',
  red_dim = '#B24E43',
  red_bright = '#DC725D',
  yellow = '#DCAA68',
  yellow_bright = '#EEC287',
  yellow_light = '#D4B482',
  yellow_dim = '#CE9C65',
  debug = '#FF00FF',
}
