-- Generated by scripts/gen-hsluv-palette.lua. Do not edit by hand.
--
-- Dusk: a deep base with warm chroma carried into the neutrals.
--
-- Built from HSLuv specs so every ramp steps evenly in perceived
-- lightness. Edit the spec in the generator and run it again.

return {
  bg_stark = '#0B0908',
  bg_dim = '#14100F',
  bg0 = '#1B1715',
  bg1 = '#221D1B',
  bg2 = '#292321',
  bg3 = '#312A27',
  bg4 = '#38302E',
  bg5 = '#403734',
  bg_select = '#443F35',
  bg_bright = '#605949',
  fg_bright = '#EAD5A8',
  fg0 = '#E6CC98',
  fg1 = '#DFBF85',
  fg2 = '#D8B273',
  fg3 = '#D2A55F',
  fg4 = '#CC974C',
  fg5 = '#C68A36',
  fg_dim = '#CBAC7C',
  grey0 = '#4F4B3C',
  grey1 = '#66614E',
  grey2 = '#7D7761',
  blue = '#80885F',
  cyan = '#77936C',
  green = '#929457',
  green_dim = '#747449',
  orange = '#DA7638',
  orange_dim = '#92532B',
  red = '#D18263',
  red_dim = '#BB2C2D',
  red_bright = '#E85541',
  yellow = '#E19E3F',
  yellow_bright = '#F8B862',
  yellow_light = '#DBAB65',
  yellow_dim = '#D08D41',
  debug = '#FF00FF',
}
