-- Generate experimental palettes from HSLuv specs.
--
-- A spec states each ramp as a hue, a saturation, and a lightness range. The
-- generator spaces lightness evenly across the range, so every ramp is even in
-- perception by construction rather than by hand.
--
-- Run from the repo root, inside the dev shell:
--   nix develop --command lua scripts/gen-hsluv-palette.lua
--
-- Writes lua/torchlight/palettes/<name>.lua and colors/torchlight-<name>.lua
-- for every spec below. The output holds plain hex strings, so nvim never
-- loads hsluv at runtime.
--
-- The generated files are the source of truth for nvim, but not for a change:
-- edit the spec and run this again.

package.path = './lua/?.lua;./lua/?/init.lua;' .. package.path

local hsluv = require('hsluv')

-- Key order in the written file, grouped the way the palette reads rather
-- than alphabetically, so a diff between candidates lines up by role.
local KEY_ORDER = {
  'bg_stark',
  'bg_dim',
  'bg0',
  'bg1',
  'bg2',
  'bg3',
  'bg4',
  'bg5',
  'bg_select',
  'bg_bright',
  'fg_bright',
  'fg0',
  'fg1',
  'fg2',
  'fg3',
  'fg4',
  'fg5',
  'fg_dim',
  'grey0',
  'grey1',
  'grey2',
  'blue',
  'cyan',
  'green',
  'green_dim',
  'orange',
  'orange_dim',
  'red',
  'red_dim',
  'red_bright',
  'yellow',
  'yellow_bright',
  'yellow_light',
  'yellow_dim',
  'debug',
}

--- Interpolate n values across [from, to]. A single step sits at `from`.
local function spread(from, to, n)
  local out = {}
  for i = 1, n do
    out[i] = n == 1 and from or from + (to - from) * (i - 1) / (n - 1)
  end
  return out
end

--- Accept a scalar or a {from, to} pair for hue and saturation, so a ramp can
--- hold one steady while the other moves.
local function channel(value, n)
  if type(value) == 'table' then
    return spread(value[1], value[2], n)
  end
  return spread(value, value, n)
end

--- HSLuv saturation is a share of the most chroma sRGB can hold at that
--- lightness and hue, and that ceiling collapses as lightness rises. Holding
--- saturation steady up a ramp therefore drains colour out of the light end: a
--- foreground at lightness 90 and saturation 44 carries less than half the
--- colour of one at lightness 85 and saturation 40. Stating chroma instead
--- fixes what the eye reads, so solve back to the saturation HSLuv wants.
local function saturation_for_chroma(l, h, c)
  return math.min(100, c / hsluv.max_safe_chroma_for_lh(l, h) * 100)
end

--- One colour from a hue and a lightness, with its colourfulness given either
--- as a saturation or as a chroma.
local function mix(h, l, s, c)
  assert((s == nil) ~= (c == nil), 'give a colour either a saturation or a chroma, not both')
  return hsluv.hsluv_to_hex({ h, c and saturation_for_chroma(l, h, c) or s, l }):upper()
end

--- Expand one spec into a flat name-to-hex table.
local function build(spec)
  local palette = {}

  for _, ramp in ipairs(spec.ramps) do
    local n = #ramp.keys
    local hues = channel(ramp.h, n)
    local lums = spread(ramp.l[1], ramp.l[2], n)
    local sats = ramp.s and channel(ramp.s, n)
    local chromas = ramp.c and channel(ramp.c, n)
    for i, key in ipairs(ramp.keys) do
      palette[key] = mix(hues[i], lums[i], sats and sats[i], chromas and chromas[i])
    end
  end

  for key, value in pairs(spec.colors) do
    if type(value) == 'string' then
      -- A literal hex passes through untouched.
      palette[key] = value
    elseif value.h then
      -- Named form, so the colour can be stated in chroma.
      palette[key] = mix(value.h, value.l, value.s, value.c)
    else
      -- Bare HSLuv triple.
      palette[key] = mix(value[1], value[3], value[2])
    end
  end

  return palette
end

local function write_palette(spec, palette)
  local lines = {
    '-- Generated by scripts/gen-hsluv-palette.lua. Do not edit by hand.',
    '--',
    '-- ' .. spec.description,
    '--',
    '-- Built from HSLuv specs so every ramp steps evenly in perceived',
    '-- lightness. Edit the spec in the generator and run it again.',
    '',
    'return {',
  }
  for _, key in ipairs(KEY_ORDER) do
    assert(palette[key], string.format('%s: spec is missing key %s', spec.name, key))
    lines[#lines + 1] = string.format("  %s = '%s',", key, palette[key])
  end
  lines[#lines + 1] = '}'
  lines[#lines + 1] = ''

  local path = 'lua/torchlight/palettes/' .. spec.name .. '.lua'
  local file = assert(io.open(path, 'w'))
  file:write(table.concat(lines, '\n'))
  file:close()
  return path
end

local function write_colorscheme(spec)
  local path = 'colors/torchlight-' .. spec.name .. '.lua'
  local file = assert(io.open(path, 'w'))
  file:write(table.concat({
    '-- Generated by scripts/gen-hsluv-palette.lua. Do not edit by hand.',
    '-- Entry point for `:colorscheme ' .. 'torchlight-' .. spec.name .. '`.',
    "require('torchlight').setup({ palette = '" .. spec.name .. "' })",
    '',
  }, '\n'))
  file:close()
  return path
end

local SPECS = dofile('scripts/palette-specs.lua')

for _, spec in ipairs(SPECS) do
  local palette = build(spec)
  print(write_palette(spec, palette))
  print(write_colorscheme(spec))
end
